server:
  port: 8801
spring:
  application:
    name: eurekaserver
eureka:
  instance:
    hostname: eureka01
  client:
  # 由于我们是作为服务端⻆色，所以不需要获取服务端，改为false，默认为true
    fetch-registry: false
  # 暂时不需要将自己也注册到Eureka
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka02:8802/eureka