fserver:
  port: 8301
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: DB990708
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: userservice
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 3a4f4100-b164-4c0e-be3e-49e4e0be6820
seata:
  service:
    vgroup-mapping:
      # 这里需要对事务组做映射，默认的分组名为 应用名称-seata-service-group，将其映射到default
      # 这个很关键，一定要配置对，不然会找不到服务
      bookservice-seata-service-group: default
    grouplist:
      default: localhost:8868