server:
  port: 8002
  spring:
    cloud:
      stream:
        binders:
          local-server:
            type: rabbit
            environment:
              spring:
                rabbitmq:
                  host: 127.0.0.1
                  port: 5672
                  username: admin
                  password: admin
                  virtual-host: /test
        bindings:
          test-in-0:
            destination: test.exchange