server:
  port: 8201
spring:
  application:
    name: borrow-service
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: DB990708
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    # 存储类型修改为redis
    store-type: redis
  redis:
    host: 127.0.0.1
security:
  oauth2:
    client: #不多说了
      client-id: web
      client-secret: 654321
    resource:
      #Token信息获取和校验地址
      token-info-uri: htt http://localhost:8500/sso/oauth/check_token
feign:
  oauth2:
#开启Oauth支持，这样就会在请求头中携带Token了
    enabled: true
#同时开启负载均衡支持
    load-balanced: true