server:
  port: 8201
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: DB990708
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: borrowservice
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 3a4f4100-b164-4c0e-be3e-49e4e0be6820
        ephemeral: false
    loadbalancer:
      nacos:
        enabled: true
    sentinel:
      transport:
        dashboard: localhost:8858