server:
  port: 8201

spring:
  application:
    name: borrowservice
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: DB990708
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://eureka01:8801/eureka, http://eureka02:8802/eureka
feign:
  circuitbreaker:
    enabled:
      true