server:
  port: 8802
spring:
  application:
    name: eurekaserver
eureka:
  instance:
    hostname: eureka02
  client:
    # 由于我们是作为服务端⻆色，所以不需要获取服务端，改为false，默认为true
    fetch-registry: false
    # 暂时不需要将自己也注册到Eureka
    register-with-eureka: false
    # 写另一个服务器地址
    service-url:
      defaultZone: http://eureka01:8801/eureka