server:
  port: 8700
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Desktop/czy/CS/SpringCloudStudy/config-repo
          default-label: main
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka, http://localhost:8802/eureka